# Generated by Django 4.1.4 on 2022-12-11 11:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('C_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.TextField(max_length=100)),
                ('Image', models.ImageField(default='default.jpg', null=True, upload_to='customer_image')),
                ('Address', models.CharField(max_length=200)),
                ('Email', models.CharField(max_length=100)),
                ('Phone', models.CharField(max_length=15)),
                ('User_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
