# Generated by Django 4.1.4 on 2022-12-11 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='User_ID',
            new_name='User',
        ),
    ]
