# Generated by Django 4.1.4 on 2022-12-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_user_id_customer_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('Pr_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Pr_Name', models.CharField(max_length=100)),
                ('Brand', models.TextField(max_length=50)),
                ('Price', models.FloatField(max_length=8)),
                ('Category', models.TextField(max_length=50)),
                ('Image', models.ImageField(default='default.jpg', null=True, upload_to='product_image')),
                ('Description', models.CharField(max_length=500)),
            ],
        ),
    ]
