# Generated by Django 4.1.4 on 2022-12-11 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('O_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Address', models.CharField(max_length=200)),
                ('Payment_Status', models.CharField(max_length=6)),
                ('C_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('Pr_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
