# Generated by Django 4.1.4 on 2022-12-11 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='C_ID',
            new_name='Cust',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Pr_ID',
            new_name='Prod',
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('Payment_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Method', models.CharField(max_length=10)),
                ('Amount', models.FloatField(max_length=8)),
                ('Ord', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('Cart_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
