# Generated by Django 4.1.4 on 2022-12-11 11:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_c_id_order_cust_rename_pr_id_order_prod_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('Review_ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Rating', models.FloatField(max_length=3)),
                ('Review_Details', models.CharField(max_length=500)),
                ('Image', models.ImageField(default='default.jpg', null=True, upload_to='review_image')),
                ('Cust', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.customer')),
                ('Prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
        ),
    ]
