# Generated by Django 4.1.4 on 2022-12-14 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_alter_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='Cart_ID',
            new_name='cart_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='C_ID',
            new_name='c_id',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Phone',
            new_name='phone',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Address',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='O_ID',
            new_name='o_id',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='Payment_Status',
            new_name='payment_status',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Method',
            new_name='method',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='Payment_ID',
            new_name='payment_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Brand',
            new_name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pr_ID',
            new_name='pr_id',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Pr_Name',
            new_name='pr_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='Price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Image',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Rating',
            new_name='rating',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Review_Details',
            new_name='review_details',
        ),
        migrations.RenameField(
            model_name='reviews',
            old_name='Review_ID',
            new_name='review_id',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Cust',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='Prod',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='User',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Cust',
        ),
        migrations.RemoveField(
            model_name='order',
            name='Prod',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='Ord',
        ),
        migrations.RemoveField(
            model_name='product',
            name='Image',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Cust',
        ),
        migrations.RemoveField(
            model_name='reviews',
            name='Prod',
        ),
        migrations.AddField(
            model_name='cart',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='order',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='order',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='payment',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.order'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.customer'),
        ),
        migrations.AddField(
            model_name='reviews',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='store.product'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='default.jpg', null=True, upload_to='product_image'),
        ),
    ]
